import Foundation

/// A utility that produces a list of all standard f‑stop values between a given
/// minimum and maximum, stepping in one‑third‑stop increments.
///
/// The default range is from f/1 to f/22, which matches the most common
/// photographic lenses.
final class FStopCalculator {

    /// The minimum f‑stop value (inclusive). Default is 1.
    let minFStop: Double = 1.0

    /// The maximum f‑stop value (inclusive). Default is 22.
    var maxFStop: Double = 22.1

    /// The complete list of f‑stop values generated by this calculator.
    private(set) var allFStops: [Double] = []

    /// Initializes the calculator with a custom range.
    init() {
        precondition(minFStop > 0, "f‑stop must be greater than zero.")
        generateAllFStops()
    }

    /// Generates the list of f‑stops and stores it in `allFStops`.
    private func generateAllFStops() {
        // Each full stop corresponds to a factor of sqrt(2).
        // A third‑stop increment is thus sqrt(2)^(1/3).
        let stepFactor = pow(sqrt(2.0), 1.0 / 3.0)

        var currentStep = 0
        var stop = 0.0
        while stop < maxFStop {
            // Compute the aperture value for this step.
            stop = minFStop * pow(stepFactor, Double(currentStep))
            // Round to one decimal place for a clean list.
            let rounded = round(stop * 10) / 10
            allFStops.append(rounded)
            currentStep += 1
        }
    }

    /// Returns the formatted f‑stop values.
    func formattedFStops() -> [Double] {
        return allFStops
    }
}
